// Test vectors for the Python SDK's swap checks, from this SDK's built code (npm run build first):
//   node scripts/swap-vectors.mjs > ../lpsignal-python/tests/swap_vectors.json
// Bigints are written as "n<digits>". Every calldata case carries its full bytes and the TS verdict.
import { readFileSync } from 'node:fs';
import { decodeFunctionData, encodeFunctionData } from 'viem';
import { checkSwapCall, KYBER_ROUTER, KYBER_ROUTER_ABI, maxImpactBps, minOutFloor, requiredMinOut, spotOut, sqrtRatioAtTick, swapFeeBps, SwapRefused } from '../dist/liquidity/index.js';

const big = (_k, v) => (typeof v === 'bigint' ? `n${v}` : v);
const FX = JSON.parse(readFileSync(new URL('../test/fixtures/kyber-base-weth-usdc.json', import.meta.url), 'utf8'));
const ME = '0x00000000000000000000000000000000000000aa';
const WETH = '0x4200000000000000000000000000000000000006', USDC = '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913';
const real = { to: KYBER_ROUTER, data: FX.build.data, value: 0n };
const exp = { from: { token: WETH, native: false }, to: { token: USDC, native: false }, amountIn: 10n ** 16n, account: ME, feeBps: 25, minOut: 26_000_000n };
const tampered = (f) => {
  const e = decodeFunctionData({ abi: KYBER_ROUTER_ABI, data: real.data }).args[0];
  return { ...real, data: encodeFunctionData({ abi: KYBER_ROUTER_ABI, functionName: 'swap', args: [f(e)] }) };
};
const verdict = (c, e = exp) => { try { checkSwapCall(c, e); return null; } catch (x) { if (x instanceof SwapRefused) return x.message; throw x; } };
const bad = '0x0000000000000000000000000000000000000bad';
const calls = [
  ['real', real, exp],
  ['router', { ...real, to: bad }, exp],
  ['recipient', tampered((e) => ({ ...e, desc: { ...e.desc, dstReceiver: bad } })), exp],
  ['fee receiver', tampered((e) => ({ ...e, desc: { ...e.desc, feeReceivers: [bad] } })), exp],
  ['fee amount', tampered((e) => ({ ...e, desc: { ...e.desc, feeAmounts: [10n] } })), exp],
  ['second fee', tampered((e) => ({ ...e, desc: { ...e.desc, feeReceivers: [...e.desc.feeReceivers, ME], feeAmounts: [...e.desc.feeAmounts, 1n] } })), exp],
  ['fee on output', tampered((e) => ({ ...e, desc: { ...e.desc, flags: 0x2c0n } })), exp],
  ['partial fill', tampered((e) => ({ ...e, desc: { ...e.desc, flags: 0x281n } })), exp],
  ['permit', tampered((e) => ({ ...e, desc: { ...e.desc, permit: '0x1234' } })), exp],
  ['token out', tampered((e) => ({ ...e, desc: { ...e.desc, dstToken: WETH } })), exp],
  ['amount', tampered((e) => ({ ...e, desc: { ...e.desc, amount: 2n * 10n ** 16n } })), exp],
  ['split', tampered((e) => ({ ...e, desc: { ...e.desc, srcAmounts: [1n] } })), exp],
  ['minimum', tampered((e) => ({ ...e, desc: { ...e.desc, minReturnAmount: 1n } })), exp],
  ['minimum vs floor', real, { ...exp, minOut: 27_000_000n }],
  ['value', { ...real, value: 1n }, exp],
  ['native mismatch', real, { ...exp, from: { token: WETH, native: true } }],
  ['other function', { ...real, data: '0x8af033fb' + real.data.slice(10) }, exp],
  ['garbage', { ...real, data: '0xe21fd0e9' + '00'.repeat(8) }, exp],
].map(([name, c, e]) => ({ name, call: c, expect: e, verdict: verdict(c, e) }));

const sp = [-200000, -887000, 0, 200000, 887000].map((t) => sqrtRatioAtTick(t));
const spot = [];
for (const s of sp) for (const in0 of [true, false]) for (const [a, f] of [[1n, 25], [10n ** 18n, 25], [123_456_789n, 5], [10n ** 30n, 0]]) spot.push([s, in0, a, f, spotOut(s, in0, a, f)]);
const floor = [[1_000_000n, 300, 50], [10n ** 24n, 50, 10], [7n, 100, 9_000], [0n, 300, 50]].map(([s, i, sl]) => [s, i, sl, minOutFloor(s, i, sl)]);
const required = [
  [102_000_000n, 300, 50, 100_000_000n, 102_000_000n], [102_000_000n, 300, 50, 101_600_000n, 102_000_000n], [110_000_000n, 50, 50, 1n, 100_000_000n],
  [0n, 300, 50, 0n, 27_022_094n], [10n ** 20n, 100, 30, 10n ** 19n, 10n ** 20n],
].map(([s, i, sl, n, q]) => [s, i, sl, n, q, requiredMinOut({ spot: s, impactBps: i, slippageBps: sl, need: n, quoteOut: q })]);
const classes = ['stable', 'correlated', 'volatile', 'other'].map((c) => [c, swapFeeBps(c), maxImpactBps(c)]);
process.stdout.write(JSON.stringify({ note: 'generated by lpsignal-node scripts/swap-vectors.mjs', calls, spot, floor, required, classes }, big, 1) + '\n');
